[server]
headless = true
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#0F2A47"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F6FA"
textColor = "#0F172A"
font = "serif"
